version: "3.7"

services:
  db:
    image: mongo:4.2
    ports:
      - 27017:27017
    restart: always
    environment:
      - TZ=Europe/Madrid
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db-data:/data/db
    command: mongod --logpath=/dev/null

  node-ts:
    build:
      context: ./
      dockerfile: Dockerfile.node-dev
    environment:
      - TZ=Europe/Madrid
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - backend-build:/usr/src/app/dist
    command: npm run dev:build

  express:
    build:
      context: ./
      dockerfile: Dockerfile.express
    ports:
      - 5000:5000
      - 3333:3333
    environment:
      - TZ=Europe/Madrid
    tty: true
    volumes:
      - type: volume
        source: backend-build
        target: /app/build
    working_dir: /app
    command: sh -c './wait-for -t 30 node-ts:80 -- npm run dev:server'
    depends_on:
      - db
      - node-ts

volumes:
  db-data:
  backend-build:
